testing with role

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -9,11 +9,61 @@ jobs:
   run_job_with_aws:
     runs-on: ubuntu-latest
     environment: dev
+    env: 
+      IAM_USERS_LIST: ${{ secrets.SAFE_USERS }} 
     steps:
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@main
         with:
           role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
           aws-region: ${{ vars.AWS_REGION }}
+
       - name: Additional steps
         run: aws sts get-caller-identity 
+      
+      - name: Safety Check
+        shell: bash
+        run: |
+          IFS=',' read -r -a USERS <<< "$IAM_USERS_LIST"
+
+          SAFE_WINDOW=259200
+          CURRENT_TIME=$(date +%s)
+          
+          echo "Checking login activity for: ${USERS[@]}"
+
+          # 3. Loop through the generated array
+          for user in "${USERS[@]}"; do
+            
+            user=$(echo "$user" | xargs)
+
+            echo "Checking user: $user"
+            USER_INFO=$(aws iam get-user --user-name "$user" 2>/dev/null)
+            
+             if [ $? -ne 0 ]; then
+               echo "User $user not found. Skipping."
+               continue
+             fi
+
+             LAST_LOGIN_ISO=$(echo "$USER_INFO" | jq -r '.User.PasswordLastUsed // "None"')
+
+             if [ "$LAST_LOGIN_ISO" != "None" ]; then
+                LAST_LOGIN_TS=$(date -d "$LAST_LOGIN_ISO" +%s)
+                DIFF=$((CURRENT_TIME - LAST_LOGIN_TS))
+                
+                if [ "$DIFF" -lt "$SAFE_WINDOW" ]; then
+                  echo "🛑 STOP: User $user logged in recently. ABORTING."
+                  exit 1
+                fi
+             fi
+          done
+          
+          echo "✅ All checks passed. Proceeding to nuke..."
+
+    #   - name: Download AWS Nuke
+    #     if: success()
+    #     id: nuke-install
+    #     run: |
+    #       curl -sL https://github.com/ekristen/aws-nuke/releases/download/v3.62.2/aws-nuke-v3.62.2-linux-amd64.tar.gz -o nuke.tar.gz
+    #       tar -xzf nuke.tar.gz
+    #       ls -F
+    #       chmod +x aws-nuke
