multiple conditions

diff --git a/.github/workflows/execution-flow.yml b/.github/workflows/execution-flow.yml
--- a/.github/workflows/execution-flow.yml
+++ b/.github/workflows/execution-flow.yml
@@ -19,6 +19,8 @@ jobs:
         run: npm run lint
   test:
     runs-on: ubuntu-latest
+    outputs:
+      test-case: ${{ steps.test-case.outcome }}
     steps:
       - name: Get code
         uses: actions/checkout@v5
@@ -31,9 +33,10 @@ jobs:
       - name: Install dependencies
         run: npm ci
       - name: Test code
+        id: test-case
         run: npm run test
-        continue-on-error: true
       - name: Upload test report
+        if: steps.test-case.outcome == 'failure'
         uses: actions/upload-artifact@v4
         with:
           name: test-report
@@ -52,6 +55,11 @@ jobs:
           key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
       - name: Install dependencies
         run: npm ci
+      - name: Verify Tests Passed
+        if: needs.test.outputs.test-case != 'success'
+        run: |
+          echo "Tests failed. Stopping the build process."
+          exit 1
       - name: Build website
         id: build-website
         run: npm run build
@@ -65,10 +73,15 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Get build artifacts
+        if: needs.build.result == 'success'
+        continue-on-error: true
+        id: download-artifact
         uses: actions/download-artifact@v5
         with:
           name: dist-files
       - name: Output contents
+        if: steps.download-artifact.outcome == 'success'
+        continue-on-error: true
         run: ls
       - name: Deploy
-        run: echo "Deploying..."
+        run: echo "If you are seeing this message, then the continue-on-error worked!"
